### ISSUE TITLE
Task Dropdown

### ISSUE THREAD

**Issue by jrob8577** [GuildCrafts/floworky#119]
As a user, I want a super fancy dropdown to appear when i hover over the bullet next to a task item, so that I have access to common task interactions.

**Comment by jrob8577** [comment]
![screen shot 2016-12-19 at 1 47 46 pm](https://cloud.githubusercontent.com/assets/838110/21330317/c86cd55a-c5f1-11e6-882f-c702455f0581.png)

**Comment by tjfwalker** [comment]
Prototype: http://codepen.io/tjfwalker/pen/PbLQZg/
