### ISSUE TITLE
Edit items

### ISSUE THREAD

**Issue by jrob8577** [GuildCrafts/floworky#40]
As a user, I want to be able to edit an item's title and description, so that I can correct errors in an item.
* Editing should happen in place, without a page refresh
* Add dots to the items
* Clicking on dot will now toggle completion of the item

**Comment by Moniarchy** [comment]
@EthanJStark and I want this

**Comment by Moniarchy** [comment]
We're starting with this one!

**Comment by EthanJStark** [comment]
Team subtasks:

- [ ] Add dots to items
- [ ] Clicking on dot will now toggle completion of the item
- [ ] Editing should happen in place, without a page refresh

**Comment by EthanJStark** [comment]
[Example](http://jsfiddle.net/egstudio/aFMWg/1/) with good hover functionality
