### ISSUE TITLE
Type Checking

### ISSUE THREAD

**Issue by jrob8577** [GuildCrafts/floworky#41]
As a developer, I want to use static type checking, so that I can have more certainty about the correctness of code I add to the system
* Integrate Flow into development workflow
* Update README with instructions to set up Flow in Atom, Sublime, and console (if necessary)
* Integrate Flow into the build process

**Comment by tjfwalker** [comment]
- http://babeljs.io/docs/plugins/preset-es2015/
- https://babeljs.io/docs/usage/polyfill/
- https://babeljs.io/docs/setup/#installation

**Comment by jrob8577** [comment]
Additional blocking story identified #60 from this work.
