### ISSUE TITLE
Some users are logging in under user 1

### ISSUE THREAD

**Issue by Moniarchy** [GuildCrafts/floworky#44]
It appears that when an account is "logged into" without being signed up first, it automatically has the id of 1, which means that the items in the database have a user_id of 1. When you try to sign up with the email after you have logged in with it already, you still log in to the account with id 1. 

Recreate this issue:

- while logged out, sign into the website with a new email address.
- create an item and check the items table in the database, the user_id of the item should be 1.
- log out of the current user account.
- sign up for a new account using a different email address.
- log into the account.
- create an item and check the items table in the database, the user_id of the item should be equivalent to the user's id.

**Comment by jrob8577** [comment]
@Moniarchy I can not seem to reproduce this issue - can you grab me and help me repro?

**Comment by Moniarchy** [comment]
@jrob8577 Would love to. If we get a bio break from Homegroup I'll run over and show you
