### ISSUE TITLE
Define CSS approach

### ISSUE THREAD

**Issue by jrob8577** [GuildCrafts/floworky#48]
As a developer, I want guidelines for styling html in floworky, so that I can effectively contribute to the project.
- Resources for research: http://getbem.com/introduction/
- Create a style guide in the project that displays the visual styles along with the classes and ids we will use

**Comment by tjfwalker** [comment]
@Anasauce Here's the graphic half of Linlin's styleguide that you asked for.  
Sketch file: https://www.dropbox.com/s/yux2g6w72hc3qb2/styleguide.sketch?dl=0

As I shared with you, I think you'd have to manifest the other half of this sort of thing via [atomic](http://atomicdesign.bradfrost.com/chapter-2/) code (CAA/Sass), much like what is seen in [Bootstrap](http://getbootstrap.com/css/#buttons). In fact, [Bootstrap](http://getbootstrap.com/css/#buttons) is, I think, a great example of both halves of a good styleguide. Their docs show the styled element and describe them while along with the css code that realizes the stlyes. Bootstrap It's just way more extensive than the one you're likely looking to develop.

Other interesting things, I think, to look be aware of:

- Additional terms to build out one's understanding
  - _Design Pattern_  
    Coined by architect Christopher Alexander. A more generalized conception of a styleguide
  - _Pattern Library_  
     You will likely find styleguides by this name
One source opinion on what a styleguide is.
- [PrimerCSS | Github's Styleguide](https://github.com/styleguide)
- [A List Apart's Pattern Library](http://patterns.alistapart.com/)
- The idea of CSS Styleguide _generators_  
   These automatically create the visual and prose based half of a styleguide base on the code you already have
  - [Styledown](https://github.com/styledown/styledown) | One such generator

**Comment by jrob8577** [comment]
Closing in favor of #90
