### ISSUE TITLE
Apply styling to existing views that are already merged in to master

### ISSUE THREAD

**Issue by Anasauce** [GuildCrafts/floworky#64]
- [ ] Utilizing existing style guide apply styles to existing views in Floworky's application
- [ ] Unlink bootstrap to existing Pug views
- [ ] Check to follow BEM naming guidelines from style guide during this implementation 
- This will allow other development teams to easily add new features using styling guidelines already established

**Comment by jrob8577** [comment]
Closing in favor of #90
