### ISSUE TITLE
Add Items

### ISSUE THREAD

**Issue by jrob8577** [GuildCrafts/floworky#7]
As a user, I want to be able to enter items into the system, so that I can track my items.
* Items should be allowed to be nested under other items
* Items should have a short name/title
* Items should have a description
* Initial implementation may be synchronous

**Comment by Anasauce** [comment]
@jrob8577 this is pretty much completed. The routes for creating a new Item and for a user to render all Items on the page is written at and merged with our fork's master. Rachel is working on a another branch where she is working on the view to render the items nested on the page
